### ISSUE TITLE
Token recreated everytime

### ISSUE THREAD

**Issue by meidlinga** [claranet/terraform-azurerm-storage-sas-token#2]
Following the example it seems the token is created everytime.
Is this known, or intended?

Would it be possible (respectively is it considered good practice) to define a trigger when the token should be created, maybe some trick with enabled?

**Comment by Shr3ps** [comment]
Hello, 
yes, because we use Terraform data external program to launch a custom script, there is no "state" for this, so terraform launches the script on each apply.

You can indeed trick with the "enabled" variable or isolate this module in a separated state (so its terraform lifecycle will not be the same as your others stuff).

**Comment by meidlinga** [comment]
Hello @Shr3ps ,

Thank you for the clarification. I will do so.
